//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinoAfisha.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.FilmCrew = new HashSet<FilmCrew>();
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public decimal Rating { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int IdGenre { get; set; }
        public string DurationInMinutes { get; set; }
        public string Languages { get; set; }
        public int IdAgeLimit { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public int IdCountry { get; set; }
        public string OriginalTitle { get; set; }
        public string Poster { get; set; }
        public string Video { get; set; }
        public int IdAdministrator { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual AgeLimit AgeLimit { get; set; }
        public virtual Country Country { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmCrew> FilmCrew { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
